using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Web.Services.Enums
{
    public enum TableEnums
    {
        CodeBlueGroupMembers,
        InhouseCodesFields,
        CodeSepsisGroupMembers,
        CallQueues,
        UserRoles,
        CallReservations,
        CodeSTEMIGroupMembers,
        CodeStrokeGroupMembers,
        CodeTraumaGroupMembers,
        ConversationParticipants,
        CodesServiceLinesMapping,
        CommunicationLog,
        ControlList,
        ConsultAcknowledgments,
        OrganizationCodeStrokeFields,
        MDRoute_Counter,
        UsersSchedule,
        ChatSettings,
        OrganizationCodeSTEMIFields,
        OrganizationCodeBlueFields,
        Organizations,
        OrganizationCodeTraumaFields,
        Consults,
        ControlListDetail,
        tmpFerdeen,
        OrganizationCodeSepsisFields,
        Settings,
        CodeStrokes,
        CodeSTEMIs,
        Users,
        ActiveLogs,
        sysdiagrams,
        CodeSepsis,
        CodeBlues,
        ELMAH_Error,
        CodeTraumas,
        Departments,
        ServiceLine,
        UsersRelation,
        ConsultFields,
        States,
        CallLog,
        InteractiveVoiceResponse,
        OrganizationConsultFields,
        Roles,
        IVRSettings,
        ClinicalHours,
        FavouriteTeam,
        Components,
        UserAccess,
        ClinicalHoliday,
        ComponentAccess,
        ActiveCodes,
        ConversationChannels,
    }
}
