// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Web.DLL.Models
{
    [Table("ems_tbl_emergency_contact")]
    public partial class EmsTblEmergencyContact
    {
        [Key]
        [Column("etec_ec_id")]
        public int EtecEcId { get; set; }
        [Required]
        [Column("etec_first_name")]
        [StringLength(100)]
        public string EtecFirstName { get; set; }
        [Required]
        [Column("etec_last_name")]
        [StringLength(100)]
        public string EtecLastName { get; set; }
        [Required]
        [Column("etec_relation")]
        [StringLength(100)]
        public string EtecRelation { get; set; }
        [Required]
        [Column("etec_contact_number")]
        [StringLength(100)]
        public string EtecContactNumber { get; set; }
        [Required]
        [Column("etec_address")]
        [StringLength(100)]
        public string EtecAddress { get; set; }
        [Column("eted_employee_id")]
        public int EtedEmployeeId { get; set; }
        [Required]
        [Column("etec_created_by")]
        [StringLength(100)]
        public string EtecCreatedBy { get; set; }
        [Required]
        [Column("etec_created_by_name")]
        [StringLength(100)]
        public string EtecCreatedByName { get; set; }
        [Column("etec_created_by_date", TypeName = "datetime")]
        public DateTime EtecCreatedByDate { get; set; }
        [Required]
        [Column("etec_modified_by")]
        [StringLength(100)]
        public string EtecModifiedBy { get; set; }
        [Required]
        [Column("etec_modified_by_name")]
        [StringLength(100)]
        public string EtecModifiedByName { get; set; }
        [Column("etec_modified_by_date", TypeName = "datetime")]
        public DateTime EtecModifiedByDate { get; set; }
        [Required]
        [Column("etec_is_delete")]
        [StringLength(100)]
        public string EtecIsDelete { get; set; }

        [ForeignKey(nameof(EtedEmployeeId))]
        [InverseProperty(nameof(EmsTblEmployeeDetails.EmsTblEmergencyContact))]
        public virtual EmsTblEmployeeDetails EtedEmployee { get; set; }
    }
}