// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Web.DLL.Models
{
    [Table("ems_tbl_working_history")]
    public partial class EmsTblWorkingHistory
    {
        [Key]
        [Column("etwh_wh_id")]
        public int EtwhWhId { get; set; }
        [Required]
        [Column("etwh_company_name")]
        [StringLength(100)]
        public string EtwhCompanyName { get; set; }
        [Required]
        [Column("etwh_designation")]
        [StringLength(100)]
        public string EtwhDesignation { get; set; }
        [Column("etwh_strat_date", TypeName = "datetime")]
        public DateTime EtwhStratDate { get; set; }
        [Column("etwh_end_date", TypeName = "datetime")]
        public DateTime EtwhEndDate { get; set; }
        [Required]
        [Column("etwh_duration")]
        [StringLength(100)]
        public string EtwhDuration { get; set; }
        [Required]
        [Column("etwh_experience_letter")]
        public byte[] EtwhExperienceLetter { get; set; }
        [Column("eted_employee_id")]
        public int EtedEmployeeId { get; set; }
        [Required]
        [Column("etwh_created_by")]
        [StringLength(100)]
        public string EtwhCreatedBy { get; set; }
        [Required]
        [Column("etwh_created_by_name")]
        [StringLength(100)]
        public string EtwhCreatedByName { get; set; }
        [Column("etwh_created_by_date", TypeName = "datetime")]
        public DateTime EtwhCreatedByDate { get; set; }
        [Required]
        [Column("etwh_modified_by")]
        [StringLength(100)]
        public string EtwhModifiedBy { get; set; }
        [Required]
        [Column("etwh_modified_by_name")]
        [StringLength(100)]
        public string EtwhModifiedByName { get; set; }
        [Column("etwh_modified_by_date", TypeName = "datetime")]
        public DateTime EtwhModifiedByDate { get; set; }
        [Required]
        [Column("etwh_is_delete")]
        [StringLength(100)]
        public string EtwhIsDelete { get; set; }

        [ForeignKey(nameof(EtedEmployeeId))]
        [InverseProperty(nameof(EmsTblEmployeeDetails.EmsTblWorkingHistory))]
        public virtual EmsTblEmployeeDetails EtedEmployee { get; set; }
    }
}