// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Web.DLL.Models
{
    [Table("ems_tbl_employee_professional_details")]
    public partial class EmsTblEmployeeProfessionalDetails
    {
        [Key]
        [Column("etepd_pd_id")]
        public int EtepdPdId { get; set; }
        [Required]
        [Column("etepd_designation")]
        [StringLength(100)]
        public string EtepdDesignation { get; set; }
        [Required]
        [Column("etepd_salary")]
        [StringLength(100)]
        public string EtepdSalary { get; set; }
        [Column("etepd_joining_date", TypeName = "datetime")]
        public DateTime EtepdJoiningDate { get; set; }
        [Required]
        [Column("etepd_probation")]
        [StringLength(1)]
        public string EtepdProbation { get; set; }
        [Column("eted_employee_id")]
        public int EtedEmployeeId { get; set; }
        [Required]
        [Column("etepd_created_by")]
        [StringLength(100)]
        public string EtepdCreatedBy { get; set; }
        [Required]
        [Column("etepd_created_by_name")]
        [StringLength(100)]
        public string EtepdCreatedByName { get; set; }
        [Column("etepd_created_by_date", TypeName = "datetime")]
        public DateTime EtepdCreatedByDate { get; set; }
        [Required]
        [Column("etepd_modified_by")]
        [StringLength(100)]
        public string EtepdModifiedBy { get; set; }
        [Required]
        [Column("etepd_modified_by_name")]
        [StringLength(100)]
        public string EtepdModifiedByName { get; set; }
        [Column("etepd_modified_by_date", TypeName = "datetime")]
        public DateTime EtepdModifiedByDate { get; set; }
        [Required]
        [Column("etepd_is_delete")]
        [StringLength(100)]
        public string EtepdIsDelete { get; set; }

        [ForeignKey(nameof(EtedEmployeeId))]
        [InverseProperty(nameof(EmsTblEmployeeDetails.EmsTblEmployeeProfessionalDetails))]
        public virtual EmsTblEmployeeDetails EtedEmployee { get; set; }
    }
}