// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Web.DLL.Models
{
    [Table("ems_tbl_employee_details")]
    public partial class EmsTblEmployeeDetails
    {
        public EmsTblEmployeeDetails()
        {
            EmsTblAcademicQualification = new HashSet<EmsTblAcademicQualification>();
            EmsTblEmergencyContact = new HashSet<EmsTblEmergencyContact>();
            EmsTblEmployeeProfessionalDetails = new HashSet<EmsTblEmployeeProfessionalDetails>();
            EmsTblProfessionalQualification = new HashSet<EmsTblProfessionalQualification>();
            EmsTblWorkingHistory = new HashSet<EmsTblWorkingHistory>();
        }

        [Key]
        [Column("eted_employee_id")]
        public int EtedEmployeeId { get; set; }
        [Column("eted_first_name")]
        [StringLength(50)]
        public string EtedFirstName { get; set; }
        [Column("eted_last_name")]
        [StringLength(50)]
        public string EtedLastName { get; set; }
        [Column("eted_email_address")]
        [StringLength(50)]
        public string EtedEmailAddress { get; set; }
        [Column("eted_dob", TypeName = "date")]
        public DateTime? EtedDob { get; set; }
        [Column("eted_contact_number")]
        [StringLength(50)]
        public string EtedContactNumber { get; set; }
        [Column("eted_address")]
        [StringLength(50)]
        public string EtedAddress { get; set; }
        [Column("eted_gender")]
        [StringLength(50)]
        public string EtedGender { get; set; }
        [Column("eted_marital_status")]
        [StringLength(50)]
        public string EtedMaritalStatus { get; set; }
        [Column("eted_blood_group")]
        [StringLength(50)]
        public string EtedBloodGroup { get; set; }
        [Required]
        [Column("eted_created_by")]
        [StringLength(100)]
        public string EtedCreatedBy { get; set; }
        [Required]
        [Column("eted_created_by_name")]
        [StringLength(100)]
        public string EtedCreatedByName { get; set; }
        [Column("eted_created_by_date", TypeName = "datetime")]
        public DateTime EtedCreatedByDate { get; set; }
        [Required]
        [Column("eted_modified_by")]
        [StringLength(100)]
        public string EtedModifiedBy { get; set; }
        [Required]
        [Column("eted_modified_by_name")]
        [StringLength(100)]
        public string EtedModifiedByName { get; set; }
        [Column("eted_modified_by_date", TypeName = "datetime")]
        public DateTime EtedModifiedByDate { get; set; }
        [Required]
        [Column("eted_is_delete")]
        [StringLength(100)]
        public string EtedIsDelete { get; set; }
        [Required]
        [Column("eted_photograph")]
        public byte[] EtedPhotograph { get; set; }
        [Column("eted_cnic")]
        public int EtedCnic { get; set; }
        [Required]
        [Column("eted_official_email_address")]
        [StringLength(100)]
        public string EtedOfficialEmailAddress { get; set; }
        [Required]
        [Column("eted_religion")]
        [StringLength(100)]
        public string EtedReligion { get; set; }
        [Required]
        [Column("eted_nationality")]
        [StringLength(100)]
        public string EtedNationality { get; set; }
        [Required]
        [Column("eted_status")]
        [StringLength(100)]
        public string EtedStatus { get; set; }

        [InverseProperty("EtedEmployee")]
        public virtual ICollection<EmsTblAcademicQualification> EmsTblAcademicQualification { get; set; }
        [InverseProperty("EtedEmployee")]
        public virtual ICollection<EmsTblEmergencyContact> EmsTblEmergencyContact { get; set; }
        [InverseProperty("EtedEmployee")]
        public virtual ICollection<EmsTblEmployeeProfessionalDetails> EmsTblEmployeeProfessionalDetails { get; set; }
        [InverseProperty("EtedEmployee")]
        public virtual ICollection<EmsTblProfessionalQualification> EmsTblProfessionalQualification { get; set; }
        [InverseProperty("EtedEmployee")]
        public virtual ICollection<EmsTblWorkingHistory> EmsTblWorkingHistory { get; set; }
    }
}